class DocumentFieldsSerializer < ActiveModel::Serializer
  attributes :id,
  :field_name,
  :agreement_id,
  :val,
  :value,
  :enclosed_text,
  :top,
  :left,
  :height,
  :font_style,
  :font_size,
  :font_color,
  :font_weight,
  :font,
  :border_color,
  :border_width,
  :border_style,
  :underline,
  :italic,
  :background_color,
  :margin,
  :class_name,
  :class_name_1,
  :component_type,
  :component_name,
  :component,
  :created_at,
  :updated_at
  # has_many :flats
  # has_many :inspections
end
